### ISSUE TITLE
The extension is incompatible with the GNOME version 43

### ISSUE THREAD

**Issue by penteho** [fthx/babar-lite#2]
Thanks for help!

**Comment by fthx** [comment]
Could you paste here some errors (search "fthx" and "js") in logs ?

**Comment by fthx** [comment]
I do not use GS 43, so I need help as I don't have the time to install a VM.

**Comment by nielsonrolim** [comment]
I opened a quick PR to add support to Gnome 43: https://github.com/fthx/babar-lite/pull/3

I am using it already on Gnome 43 and Fedora 37 and it is working fine.

**Comment by fthx** [comment]
I'll do extensions work next week.

Have you tried this one:
https://extensions.gnome.org/extension/5143/dashbar/
?
I don't remember if I've already asked you.

**Comment by nielsonrolim** [comment]
> I'll do extensions work next week.
> 
> Have you tried this one: https://extensions.gnome.org/extension/5143/dashbar/ ? I don't remember if I've already asked you.

Yeah, I tried Dashbar. It is nice, but I like Babar better :)

Babar shows only my open applications grouped by workspace.

Thank you for your work on these extensions. They are really great.

**Comment by emascandam** [comment]
For those who want to enable the extension for Gnome 43 before the dev adds support to it officially (hopefully soon :100: ), do this:

1. Get Matt Jakeman's [ExtensionManager](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager).
2. In the overflow menu, toggle **show unsupported**.
3. Go to browse and search for BaBar Lite. Click on the **Unsupported** button; it will show a warning but will allow you to install the extension.
4. Go to /home/$USER/.local/share/gnome-shell/extensions/babar-lite@fthx & open the 'metadata.json' file using a text editor.
5. After "42", add a comma, followed by a new line, followed by "43"

```
  "shell-version": [
    "40",
    "41",
    "42",
    "43"
  ],
```
6. Save the file and then log out and log back in. If the extension is not enabled, enable it manually from the Extension Manager application.

One of my must-have extensions, thanks for your work @fthx.

**Comment by fthx** [comment]
Let's try soon:
https://extensions.gnome.org/extension/6556/task-up/
that is the new BaBar
(you can DL it from github, the extension is working without bugs afaics)
